### ISSUE TITLE
libssh2 fails to connect and gives an error after recent libssh2 update

### ISSUE THREAD

**Issue by willbprog127** [libssh2/libssh2#640] opened 2021-11-09 18:24 UTC
After a recent update of libssh2 (currently 1.8.0-2.1build1 on Linux Mint), SSH connections using libssh2 now fail with error -5 `LIBSSH2_ERROR_KEX_FAILURE`.  The SSH server complains that libssh2 is using RSA keys when the key being used was actually generated using ssh-ed25519.  

> sshd: PID 2116: Unable to negotiate with xx.xx.xx.xx port 51890: no matching host key type found. Their offer: ssh-rsa,ssh-dss [preauth]

None of my app's code was changed to cause this issue, it happened after the libssh2 update.  Before the latest libssh2 update, my app could connect successfully and there were no errors.  This is on both Linux Mint and now macOS Catalina using the libssh2 port from MacPorts.

The failure and error happens when I execute `libssh2_session_handshake(sshSession, sockSSHSock)` in my app when I attempt to connect to the SSH server.  I am using an IPv4 address and connecting to an OpenSSH server.

The code sample would be too large to post here, but please understand I made absolutely zero changes to my code and no changes to the private/public keys being used.

Connecting using the systems' `ssh` command works fine using the same key, so it appears to be a libssh2 issue.

**Version**
 - OS: Linux Mint 20.2 'Uma', macOS Catalina / MacPorts
 - libssh2 version 1.8.0-2.1build1 on Linux Mint, version 1.9.0_1 on macOS / MacPorts

**Comment by willco007** [comment] 2021-11-09 18:26
Did you happen to update your OpenSSH server to 8.8? It's likely this issue: #630

**Comment by willbprog127** [comment] 2021-11-09 18:31
> Did you happen to update your OpenSSH server to 8.8? It's likely this issue: #630

Hi @willco007.  Yes, on macOS / MacPorts, OpenSSH is at openssh @8.8p1_1.  I'm not on Linux at the moment but I suspect that might be the case there, as well.  I'll check out that issue and see if it applies.  Thanks! 👍

**Comment by willco007** [comment] 2021-11-09 18:35
I'm going to close this as a duplicate of #630. You can check the OpenSSH 8.8 release notes on how to re-enable sha1 RSA keys or change to a different key type until we get a release out. There is a PR open to resolve this issue, you can take a look at if you want to verify the issue. https://github.com/libssh2/libssh2/pull/626

**Closed by willco007** 2021-11-09 18:35 UTC

**Comment by willbprog127** [comment] 2021-11-09 18:42
> You can check the OpenSSH 8.8 release notes on how to re-enable sha1 RSA keys or change to a different key type until we get a release out.

But I'm not using RSA keys, I'm using ssh-ed25519.  Do I still have to do a workaround?

Thanks :smiley:

**Comment by willco007** [comment] 2021-11-09 18:46
You're using an out of date version of libssh2 (1.8) that doesn't support ed-25519 keys at all. It is attempting to use RSA key auth according to your log: `sshd: PID 2116: Unable to negotiate with xx.xx.xx.xx port 51890: no matching host key type found. Their offer: ssh-rsa,ssh-dss [preauth]`.

**Comment by willbprog127** [comment] 2021-11-09 18:48
> You're using an out of date version of libssh2 (1.8) that doesn't support ed-25519 keys at all. It is attempting to use RSA key auth according to your log

Odd.  It was using ed-25519 keys fine before the latest (OpenSSH?) update, so now I'm really confused :confused: I guess I'll just have to remove libssh2 and try to use the system's `ssh` client instead.  Thanks for the help :+1:

**Comment by willco007** [comment] 2021-11-09 18:49
Please update to the latest libssh2 (1.10) on all your systems and try again if you're using ed-25519 keys.
