### ISSUE TITLE
LIBSSH2_VERSION contains "_DEV" when checking out the commit tagged by libssh2-1.11.1

### ISSUE THREAD

**Issue by logmanoriginal** [libssh2/libssh2#1473] opened 2024-10-18 10:13 UTC
**Describe the bug**
The commit tagged by [`libssh2-1.11.1`](https://github.com/libssh2/libssh2/tree/libssh2-1.11.1) sets `LIBSSH2_VERSION` to "1.11.1_DEV" and `LIBSSH2_TIMESTAMP` to "DEV":
https://github.com/libssh2/libssh2/blob/a312b43325e3383c865a87bb1d26cb52e3292641/include/libssh2.h#L51
https://github.com/libssh2/libssh2/blob/a312b43325e3383c865a87bb1d26cb52e3292641/include/libssh2.h#L85

**To Reproduce**
Checkout [`libssh2-1.11.1`](https://github.com/libssh2/libssh2/tree/libssh2-1.11.1) and review the values for `LIBSSH2_VERSION` and `LIBSSH2_TIMESTAMP`.

**Expected behavior**
* `LIBSSH2_VERSION` should be set to "1.11.1"
* `LIBSSH2_TIMESTAMP` should be set to the release time.

**Version (please complete the following information):**
 - OS and version: Windows
 - libssh2 version: 1.11.1
 - crypto backend and version: WinCNG

**Additional context**
The release tarballs are correct.

**Comment by dfandrich** [comment] 2024-10-18 18:15
Duplicate of #771

**Comment by logmanoriginal** [comment] 2024-10-18 19:46
I see. So we cannot rely on source tags and GitHub packages.

> The _blessed_ and _signed_ releases are provided on libssh2.org. Any other archives, like the ones generated by GitHub are just a collection of files from the tag.. They are not the official releases.

This should be explained in the header file to avoid confusion. Tags are typically associated with release versions and a tagged commit should represent the exact source version used for the corresponding release.

**Comment by logmanoriginal** [comment] 2024-10-22 15:06
Thanks. You are right the timestamp was never set. This is actually explained in the headers had I read it properly. Sorry about that.

Since both are set only in the release tarballs, I added the corresponding explanation to LIBSSH2_VERSION in #1475. Maybe this helps anyone who stumbling over it in the future.

**Comment by vszakats** [comment] 2024-10-22 23:17
Fixed by 83590ac70d63eda7d4229efc92b5734b1a76c96f #1475

**Comment by vszakats** [comment] 2024-10-22 23:18
Fixed by 83590ac70d63eda7d4229efc92b5734b1a76c96f #1475

**Closed by vszakats** 2024-10-22 23:18 UTC
Labels: duplicate
