### ISSUE TITLE
AWS connection with RSA private key is not working

### ISSUE THREAD

**Issue by HardikMoon** [libssh2/libssh2#1005] opened 2023-04-26 04:38 UTC
**Describe the bug**
AWS connection with RSA private key is not working

**To Reproduce**
We are trying to connect the AWS server with the pem file but not working in that case. Same Pem file We tried it in another application and it's working. here is the error message I receive.
Error is: authenticationFailed(detail: "Username/PublicKey combination invalid")

 let publicKey  = "/Users/hardik.d/Library/Containers/com.moontechnolabs.ssh2/Data/Library/SSHClient.pem/id_rsa.pub"
 let privateKey = "/Users/hardik.d/Library/Containers/com.moontechnolabs.ssh2/Data/Library/SSHClient.pem/id_rsa"
 try self.session.authenticateByPublicKeyFromFile(username, password: password, publicKey: publicKey, privateKey: privateKey)

**Version (please complete the following information):**
 - MACOS Ventura and version: 13.3
 - libssh2 version: [e.g. 1.10.0]

**Comment by willco007** [comment] 2023-05-01 15:47
Dupe of https://github.com/libssh2/libssh2/issues/676 and https://github.com/libssh2/libssh2/issues/634 and a couple others. Updating to master will resolve this issue.

**Closed by willco007** 2023-05-01 15:47 UTC

**Comment by HardikMoon** [comment] 2023-05-02 04:34
We are using this library 
https://github.com/Frugghi/SwiftSH/issues/45

We need an update on libssh2.a framework can you please provide libssh2.a framework file with me?

**Comment by HardikMoon** [comment] 2025-01-02 11:12
Getting a same error also after the updating openssh library
