### ISSUE TITLE
LabVIEW: Key Exchange Failure Error

### ISSUE THREAD

**Issue by mar33cki** [libssh2/libssh2#780] opened 2022-12-23 11:56 UTC
**Describe the bug**
After customer Linux update cannot connect to SSH Server, using the example Password Authentication.vi. Get the error code 
 Code: -8109
Source: Field_RnD_Services_LIBSSH2_Toolkit.lvlib:Check Status.vi<ERR>
[Key Exchange Failure Error] The encryption key exchange with the remote host has failed.

While the putty ssh connection works properly.

**To Reproduce**
Eth interface configured to static IP 192.168.1.10, SSH Server IP 192.168.1.1. Run LIBSSH2 example Password Authentication.vi

**Expected behavior**
Authenticated, 

**Version (please complete the following information):**
 - OS and version: [Windows]
 - libssh2 version: [0.1.0] - 2020-04-17
 - crypto backend: [SSH]

**Comment by dfandrich** [comment] 2022-12-23 17:59
This sounds like a dupe of #676

**Comment by mar33cki** [comment] 2022-12-27 09:18
but how to solve it? Is there any way to create an known host list?
via putty I can get the RSA-SHA256 key

**Closed** 2023-02-25 03:17 UTC
