### ISSUE TITLE
LIBSSH2_CHANNEL struct can be shared between the threads in c++??

### ISSUE THREAD

**Issue by RichaMehtaN** [libssh2/libssh2#279] opened 2019-01-08 05:39 UTC
I want to share the ssh session and channels between the threads but as per the introduction for thread safety, it is written there not to share handles between threads so is it safe to share the ssh channels between threads in C++??

**Comment by bagder** [comment] 2019-03-17 00:04
Please ask questions on the mailing list, we use the issue tracker for bugs only.

**Comment by willco007** [comment] 2019-05-08 18:05
Closing since this is not a bug report.

**Closed by willco007** 2019-05-08 18:05 UTC
