### ISSUE TITLE
Error while buidling libssh2 v1.11 using nmake and nmakefile in WINDOWS

### ISSUE THREAD

**Issue by devdatt9129** [libssh2/libssh2#1256] opened 2023-11-30 05:32 UTC
**Describe the bug**
I am trying to build libssh2 v1.11 as a static library in windows using nmake and nmakefile, 
This is the command which i gave:
nmake -f NMakefile TARGET=Release OPENSSL_PATH="sample path" ZLIB_PATH="sample path"

The error shown is:
NMAKE : fatal error U1073: don't know how to make 'Release/'
Stop.

**To Reproduce**
Steps to reproduce the behavior.

A recipe or example code that reproduces the problem? A stack trace from a crash

**Expected behavior**
I want to build libssh2 statically so as to use it in my codebase. 

**Version (please complete the following information):**
 - OS and version: Windows 8
 - libssh2 version: 1.11.0
 - crypto backend and version: OpenSSL

**Additional context**

**Comment by vszakats** [comment] 2023-11-30 10:08
Duplicate of https://github.com/libssh2/libssh2/discussions/1129.

**Closed** 2023-12-01 06:50 UTC
Labels: duplicate
