### ISSUE TITLE
1.9.0 release ?

### ISSUE THREAD

**Issue by manibee** [libssh2/libssh2#303] opened 2019-03-04 06:23 UTC
Libssh2-1.8.0 was released in October 2016 and no newer releases come after that. 

Is there any plan to make an official release of 1.9.0 soon?

**Comment by kdudka** [comment] 2019-03-04 07:29
See https://github.com/libssh2/libssh2/issues/277#issuecomment-454787497 .

**Comment by bagder** [comment] 2019-03-04 15:49
Duplicate of #277

**Closed by bagder** 2019-03-04 15:49 UTC
