### ISSUE TITLE
Host key fingerprint validation only supports ssh-rsa (sha-1 hashing)

### ISSUE THREAD

**Issue by jeffding45** [libssh2/libssh2#627] opened 2021-09-10 19:09 UTC
**Describe the bug**
It appears when doing key exchange, the host key fingerprint is validated only against a sha-1 hashing algorithm and doesn't support more advanced sha2-256 or sha2-512 algorithms.  If sha-1 hashing is disabled on the SSH server, key exchange fails.

**To Reproduce**
For example, this function in kex.c fails without the hostkey containing the text "ssh-rsa".

    if(kex_agree_kex_hostkey(session, kex, kex_len, hostkey, hostkey_len)) {
        return -1;
    }

Example data:
kex = curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-1.3.132.0.10,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group15-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,gss-gex-sha1-toWM5Slw5Ew8Mqkay+al2g==,gss-group15-sha512-toWM5Slw5Ew8Mqkay+al2g==,gss-group14-sha256-toWM5Slw5Ew8Mqkay+al2g==,gss-group14-sha1-toWM5Slw5Ew8Mqkay+al2g==,ext-info-s

If hostkey = "rsa-sha2-512,rsa-sha2-256,ssh-rsa", the resulting hostkey becomes ssh-rsa

    _libssh2_debug(session, LIBSSH2_TRACE_KEX, "Agreed on HOSTKEY method: %s",
                   session->hostkey->name);
    name = 'ssh-rsa'

if hostkey = "rsa-sha2-512,rsa-sha2-256", the key exchange fails and this function returns -1.

The ssh server has 3 different signature settings that can be enabled or disabled, which directly correlate to the hostkey field sent to the client.

**Expected behavior**
hostkey method should support sha2-256 and sha2-512 fingerprint checking methods.

Using libssh2 for sftp logins for example should support key exchange when only sha2 methods are available.  Alternate sftp tools like FileZilla and psftp are able to perform key exchanges.

PSFTP transcript showing key exchange to host:

Remote version: SSH-2.0-8.48 FlowSsh: Bitvise SSH Server (WinSSHD) 8.48
Using SSH protocol version 2
No GSSAPI security context available
Doing ECDH key exchange with curve Curve25519 and hash SHA-256 (unaccelerated)
Server also has rsa-sha2-256 host key, but we don't know it

**Version (please complete the following information):**
 - OS: Windows 10, Windows Server 2012 R2
 - libssh2 version: 1.10.0

**Additional context**
Primarily testing with curl connecting to sftp server.  Built a debug version of curl and via debugging can see the key exchange failures occuring within the libssh2 library.

curl 7.66.0 (i386-pc-win32) libcurl/7.66.0 OpenSSL/1.1.1l zlib/1.2.11 libssh2/1.10.0
Release-Date: 2019-09-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet t
ftp
Features: AsynchDNS Debug HTTPS-proxy IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI libz

curl debug showing the failure:

* STATE: INIT => CONNECT handle 0xf63d90; line 1491 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => WAITRESOLVE handle 0xf63d90; line 1532 (connection #0)
*   Trying x.x.x.x:22...
* TCP_NODELAY set
* STATE: WAITRESOLVE => WAITCONNECT handle 0xf63d90; line 1611 (connection #0)
* Connected to name (x.x.x.x) port 22 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0xf63d90; line 1667 (connection #0)
* Marked for [keep alive]: SSH default
* SFTP 0xf63838 state change from SSH_STOP to SSH_INIT
* SFTP 0xf63838 state change from SSH_INIT to SSH_S_STARTUP
* STATE: SENDPROTOCONNECT => PROTOCONNECT handle 0xf63d90; line 1682 (connection #0)
* Failure establishing ssh session: -5, Unable to exchange encryption keys
* SFTP 0xf63838 state change from SSH_S_STARTUP to SSH_SESSION_FREE
* Marked for [closure]: SSH session free
* SFTP 0xf63838 state change from SSH_SESSION_FREE to SSH_STOP
* multi_done
* SSH DISCONNECT starts now
* SSH DISCONNECT is done
* Closing connection 0

**Comment by willco007** [comment] 2021-09-10 19:42
Thanks for the report, this is a duplicate of #536.

**Closed by willco007** 2021-09-10 19:42 UTC
