### ISSUE TITLE
1.8.1 release?

### ISSUE THREAD

**Issue by edgan** [libssh2/libssh2#283] opened 2019-02-05 22:58 UTC
I recently ran into a bug with libssh2 1.8.0 and salt on Fedora 29. The fix was to update to a daily snapshot of 1.8.1. I previously hadn't noticed this bug running on Ubuntu, because they have made a 1.8.1 snapshot package, but Fedora has stuck to the official release. Which is why a new release would be nice. In the case of salt it seemed to completely break the use case of salt of libssh2, which is using it to connect to git repositories via ssh.

Is there any plan to make an official release of 1.8.1 soon?

https://github.com/saltstack/salt/issues/51495

**Comment by Pernat1y** [comment] 2019-02-13 15:59
More then 2 years since last stable version. It even may be 1.9 :)

**Comment by kdudka** [comment] 2019-02-13 16:10
See https://github.com/libssh2/libssh2/issues/277#issuecomment-454787497 .

**Comment by bagder** [comment] 2019-03-04 15:49
Duplicate of #277

**Closed by bagder** 2019-03-04 15:49 UTC
