### ISSUE TITLE
cmake fails to find source files in test folder although they are there

### ISSUE THREAD

**Issue by Mipsters** [libssh2/libssh2#537] opened 2020-11-27 10:25 UTC
**Describe the bug**
I tried to build ssh2, but it fails generating the build files

**To Reproduce**
```bash
mkdir bin
cd bin
cmake ..
```

log
```
-- The C compiler identification is GNU 3.3.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenSSL: /usr/local/lib/libssl.so;/usr/local/lib/libcrypto.so (found version "1.1.1f")
-- Looking for EVP_aes_128_ctr
-- Looking for EVP_aes_128_ctr - found
-- Looking for include file unistd.h
```
...
```
-- The following features have been enabled:

 * diffie-hellman-group-exchange-sha1 , "new" diffie-hellman-group-exchange-sha1 method

-- The following OPTIONAL packages have been found:

 * OpenSSL

-- The following features have been disabled:

 * Shared library , creating libssh2 as a shared library (.so/.dll)
 * Compression , using zlib for compression
 * "none" cipher
 * "none" MAC
 * Logging , Logging of execution with debug trace

-- Configuring done
CMake Error at tests/CMakeLists.txt:155 (add_executable):
  Cannot find source file:

    test_public_key_auth_succeeds_with_correct_ed25519_key_from_mem.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error at tests/CMakeLists.txt:155 (add_executable):
  Cannot find source file:

    test_public_key_auth_succeeds_with_correct_ed25519_key.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error at tests/CMakeLists.txt:155 (add_executable):
  Cannot find source file:

    test_public_key_auth_succeeds_with_correct_encrypted_ed25519_key.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: test_public_key_auth_succeeds_with_correct_ed25519_key_from_mem
CMake Error: Cannot determine link language for target "test_public_key_auth_succeeds_with_correct_ed25519_key_from_mem".
CMake Error: CMake can not determine linker language for target: test_public_key_auth_succeeds_with_correct_ed25519_key
CMake Error: Cannot determine link language for target "test_public_key_auth_succeeds_with_correct_ed25519_key".
CMake Error: CMake can not determine linker language for target: test_public_key_auth_succeeds_with_correct_encrypted_ed25519_key
CMake Error: Cannot determine link language for target "test_public_key_auth_succeeds_with_correct_encrypted_ed25519_key".
-- Generating done
-- Build files have been written to: /home/mipster/Projects/libssh2-1.9.0/bin
```

**Expected behavior**
for cmake to be able to find the needed files from the test folder

**Version (please complete the following information):**
 - OS: debian 3.1 (yes, it is very old)
 - libssh2 version 1.9.0

**Additional context**
- cmake: 3.6.3 (self built)
- building with `-DBUILD_TESTING=OFF` works

**Comment by willco007** [comment] 2020-11-30 20:07
Duplicate of #379.

**Closed by willco007** 2020-11-30 20:07 UTC
