### ISSUE TITLE
compilation fails with visual studio 2015

### ISSUE THREAD

**Issue by MrHacky** [libssh2/libssh2#33] opened 2015-07-21 07:41 UTC
I get the following compile error:
3>...\src\libssh2_config.h(92): error C2375: 'snprintf': redefinition; different linkage
3>    C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1932): note: see declaration of 'snprintf'
3>    global.c

Seems like msvc 2015 started providing snprintf.

**Comment by MrHacky** [comment] 2015-07-21 07:42
note i'm using the cmake build system

**Comment by havoc-io** [comment] 2015-07-21 10:35
I had the exact same problem a few weeks back with the 2015 RC.  I was hoping it'd be fixed in the RTM version, but it seems like it's not.  If you manage to fix `snprintf` detection, you'll find that `strtoll` detection is broken as well.

My feeling is that this is actually a CMake bug.  It seems like CMake is not detecting symbols in the new [Universal CRT](http://blogs.msdn.com/b/vcblog/archive/2015/03/03/introducing-the-universal-crt.aspx) correctly.  The problem is that `check_function_exists` (and even `check_symbol_exists`) don't seem to pick up symbols (or at least all of them) correctly.  I even tried writing a little standalone CMake project to see if this detection worked and it did not, so I'm not sure it's something libssh2 can properly fix.

What I've done for now is [patched `libssh2/src/CMakeLists.txt`](https://gist.github.com/havoc-io/46ac990b3e6b2a6d088e) (note: this is not the root CMakeLists.txt but rather the one in src/) to force detection of these two symbols.  It is not elegant, but it seems to build and function correctly as far as I can tell.  I don't think this is the right long-term solution though.

**Comment by alamaison** [comment] 2015-07-25 22:21
Can you test with the latest master (af14462d535a2b061a77d31d60734ebb558aca16)?

**Comment by MrHacky** [comment] 2015-07-29 09:26
it didn't seem to work at first, but after creating a new cmake build dir everything worked (i guess the old HAVE_SNPRINTF value was still in the cmake cache)

**Comment by alamaison** [comment] 2015-07-29 19:58
Makes sense.  The fix was to use `check_symbol_exists` instead of `check_function_exists`.  The former catches a much wider class of functions---in this case, inline functions---than the former which only detects a cdecl function exported from a library.

**Closed by alamaison** 2015-07-29 19:58 UTC

**Comment by yacine-harbi** [comment] 2015-10-10 14:14
If you're still using the win32 make file, this worked for me :

Replace 

```cpp
#define snprintf _snprintf
```
with 

```cpp
#if _MSC_VER < 1900
#define snprintf _snprintf
#endif
```

in win32/libssh2_config.h
