### ISSUE TITLE
libssh2_session_handshake is failing

### ISSUE THREAD

**Issue by jagadishthadakamalla** [libssh2/libssh2#182] opened 2017-05-16 13:53 UTC
Hello,

I have been using libssh2-version 1.3.0 since few years. But suddenly, i could not able to connect to my network over SSH. When I explored my code, I found that libssh2_session_handshake(..) method is failing with return value -5. What is this return code value and what could be the reason for this failure?

Any suggestion please.

Thanks.

**Comment by willco007** [comment] 2017-05-16 16:51
-5 is key exchange failure.  The server you’re connecting to likely tightened their security and the old version of libssh2 you’re using does not support the ciphers the server has enabled.  I would recommend updating to the latest version and talking to your sever admin about the ciphers they have enabled.  This is not a bug in libssh2 and I'm going to close this issue.

**Closed by willco007** 2017-05-16 16:51 UTC

**Comment by jagadishthadakamalla** [comment] 2017-05-16 17:03
Hello,

Thanks for your mail and information.
Can you also please check whether you have any idea on the issues 181 and
183.

If you have latest libssh2.dll for Windows, can you please share them as I
am getting linker errors while building latest libssh2 packages.

Regards
Jagadish Thadakamalla.


On 16 May 2017 22:21, "Will Cosgrove" <notifications@github.com> wrote:

-5 is key exchange failure. The server you’re connecting to likely
tightened their security and the old version of libssh2 you’re using does
not support the ciphers the server has enabled. I would recommend updating
to the latest version and talking to your sever admin about the ciphers
they have enabled. This is not a bug in libssh2 and I'm going to close this
issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/libssh2/libssh2/issues/182#issuecomment-301845187>, or mute
the thread

**Comment by jagadishthadakamalla** [comment] 2017-05-16 17:05
Hello, 

Thanks for your mail and information. 
Can you also please check whether you have any idea on the issues 181 and 183.

If you have latest libssh2.dll for Windows, can you please share them as I am getting linker errors while building latest libssh2 packages.

**Comment by willco007** [comment] 2017-05-16 17:06
I don't use/work-on the Windows side of things so you'll have to either email the dev email list (recommended) or see if anyone responds to your reported issues.
